[bootstrap.brew.taps]
"frealmyr/homebrew-tap" = "https://github.com/frealmyr/homebrew-tap.git" # topaz-denoise-ai

[bootstrap.packages]
"brew-cask:affinity-designer" = "latest"
"brew-cask:affinity-photo" = "latest"
"brew-cask:affinity-publisher" = "latest"
"brew-cask:audacity" = "latest"
"brew-cask:balenaetcher" = "latest"
"brew-cask:betterdisplay" = "latest"
"brew-cask:breaktimer" = "latest"
"brew-cask:calibre" = "latest"
"brew-cask:darktable" = "latest"
"brew-cask:digikam" = "latest"
"brew-cask:firefox" = "latest"
"brew-cask:font-atkinson-hyperlegible" = "latest"
"brew-cask:font-fira-code-nerd-font" = "latest"
"brew-cask:font-fira-mono-nerd-font" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:google-chrome" = "latest"
"brew-cask:halloy" = "latest"
"brew-cask:hyperbackupexplorer" = "latest"
"brew-cask:jellyfin-media-player" = "latest"
"brew-cask:keepassxc" = "latest"
"brew-cask:lulu" = "latest"
"brew-cask:musicbrainz-picard" = "latest"
"brew-cask:netnewswire" = "latest"
"brew-cask:netspot" = "latest"
"brew-cask:obsidian" = "latest"
"brew-cask:podman-desktop" = "latest"
"brew-cask:raspberry-pi-imager" = "latest"
"brew-cask:steam" = "latest"
"brew-cask:sweet-home3d" = "latest"
"brew-cask:synology-drive" = "latest"
"brew-cask:tailscale-app" = "latest"
"brew-cask:the-unarchiver" = "latest"
"brew-cask:frealmyr/homebrew-tap/topaz-denoise-ai" = "latest"
"brew-cask:transmission" = "latest"
"brew-cask:utm" = "latest"
"brew-cask:vscodium" = "latest"
