#!/usr/bin/env sh

###########
## Mouse ##
###########

## Focus with mouse (ew)
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

## Window manipulation with mouse (nice)
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

############
## Tiling ##
############

## Default layout
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

################
## Appearance ##
################

## Padding
yabai -m config top_padding 5
yabai -m config bottom_padding 7
yabai -m config left_padding 7
yabai -m config right_padding 7
yabai -m config window_gap 7
yabai -m config window_shadow off
yabai -m config insert_feedback_color 0xFFFFDAB9

######################
## Floating Windows ##
######################

## System
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off

## Tools
yabai -m rule --add app='^Messages$' manage=off
yabai -m rule --add app='^Stats$' manage=off

## Coding
yabai -m rule --add app='IntelliJ IDEA' title='^$' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Project Structure' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Preferences' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Edit configuration' manage=off

## Office
yabai -m rule --add app='^Calculator$' manage=off
yabai -m rule --add app='^Calendar$' manage=off

## Misc
yabai -m rule --add app="^Steam$" manage=off

###################
## Event Exports ##
###################

## Workspace indicator tray
yabai -m signal --add event=mission_control_exit action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_added action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_removed action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_created action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_destroyed action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_focused action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_moved action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_resized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_minimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_deminimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'

## Refocus after closing
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
