theme = "dracula"
icons = "awesome"

[[block]]
block = "custom"
command = "~/.local/scripts/battery.sh"
json = true
interval = 300

[[block]]
block = "custom"

[[block]]
block = "custom"
command = "~/.local/scripts/wifi.sh"
json = true
interval = 300

[[block]]
block = "custom"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
