#!/usr/local/bin/zsh

# Run BulderBank CLI commands using docker

function bbc() {

# Add a random id to the docker container, so that we can run multiple instances
if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -it  \
  -u 1000:1000 \
  -v $HOME/.config/kube:/home/buldercli/.kube \
  -v $HOME/.config/gcloud:/home/buldercli/.config/gcloud \
  -e GOOGLE_APPLICATION_CREDENTIALS=/home/buldercli/.config/gcloud/application_default_credentials.json \
  docker.pkg.github.com/bulderbank/bulder-cli/bulder-cli:latest $argv
}
