#!/usr/local/bin/zsh

#
# Summon a pgadmin instance for inspecting postgres databases
#
function pgadmin_k8s() {

docker run --name "pgadmin" \
  --net=pgadmin \
  -p 9595:80 \
  -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
  -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
  -d dpage/pgadmin4

echo "pgadmin now running at: http://localhost:9595"
echo "username: user@domain.com"
echo "password: SuperSecret"
echo ""

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.16"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  --net=pgadmin \
  -v $HOME/.kube/:/.kube/ \
  -p 5432:5432 \
  -p 3389:3389 \
  bitnami/kubectl:$K8S_VERSION $kns port-forward $argv[1] 5432 3389 

docker kill pgadmin && docker rm pgadmin
echo "pgadmin stopped"
}
