#!/usr/local/bin/zsh

#
# Run gcloud commands
#
function gcloud() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $(pwd):$(pwd) \
  -v "$HOME"/Desktop/gogocredentials:/root/.docker:cached \
  -v "$HOME"/.config/gcloud:/root/.config/gcloud:cached \
  -v "$HOME"/.kube:/root/.kube:cached \
  frealmyr/cloud-sdk-editors:latest gcloud $argv
}
