#!/usr/local/bin/zsh

#
# Run gcloud commands
#
function gcloud() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $(pwd):$(pwd) \
  -v "$HOME"/.config/gcloud:/root/.config/gcloud \
  173c9e2fd374 gcloud $argv
}
