#!/usr/local/bin/zsh

#
# Run gcloud gcurl commands
#
function gcurl() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $(pwd):$(pwd) \
  -v "$HOME"/.config/gcloud:/root/.config/gcloud \
  -w $(pwd) \
  frealmyr/cloud-sdk-editors:latest gcurl $argv
}
