#!/usr/local/bin/zsh

#
# Run gcloud gcurl commands
#
function gcurl() {

# Add a random id to the docker container, so that we can run multiple instances
if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -w $(pwd) \
  -v $(pwd):$(pwd) \
  -v $HOME/.config/gcloud:/home/clitools/.config/gcloud \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest gcurl $argv
}
