#!/usr/local/bin/zsh

#
# Run github-cli commands
#
function gh() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -e GH_EDITOR=vim \
  -v $HOME/.config/gh:/home/clitools/.config/gh \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest gh $argv[*]
}
