#!/usr/local/bin/zsh

# Run helm commands with docker

function helm() {

# Add a random id to the docker container, so that we can run multiple instances
if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

# Workaround for Docker creating folders as root if they don't exist
if [ ! -d "$HOME/.config/helm" ]; then
  mkdir -p $HOME/.config/helm
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -e KUBE_EDITOR=vim \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.config/kube:/home/clitools/.kube \
  -v $HOME/.config/helm:/home/clitools/.config/helm \
  -v $HOME/.config/gcloud:/home/clitools/.config/gcloud:cached \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest helm $argv
}
