#!/usr/local/bin/zsh

#
# Run kubectl commands, GKE requires gcloud for helpers
#
function k-noi() {

if [[ -z "2$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=2$RANDOM
fi

docker run --name "2$DOCKER_RAND_ID" --rm \
  -u 1000:1000 \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -e KUBE_EDITOR=vim \
  -v $HOME/.kube/config:/home/clitools/.kube/config \
  -v $HOME/.config/gcloud:/home/clitools/.config/gcloud \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl $kns $argv[*]
}

