#!/usr/local/bin/zsh

#
# K8s resource request, limits and utilizations
#
function kcap() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.config/kube:/home/clitools/.kube \
  -v $HOME/.config/gcloud:/home/clitools/.config/gcloud \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl-resource_capacity $argv[*]
}
