#!/usr/local/bin/zsh

#
# Rename the active kubectl context
#
function kcdelete() {
: ${1?"kcdelete context_to_delete"}

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -v $HOME/.kube:/home/clitools/.kube \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl config unset contexts.$argv[1]
}
