#!/usr/local/bin/zsh

#
# List every kubectl context available
#
function kcls() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -v $HOME/.config/kube:/home/clitools/.kube \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl config get-contexts
}
