#!/usr/local/bin/zsh

#
# List every kubectl context available
#
function kcls() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.14"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/config:/.kube/config \
  bitnami/kubectl:$K8S_VERSION config get-contexts
}
