#!/usr/local/bin/zsh

#
#  Watch deployments for changes
#
function know() {
: ${1?"know SECONDS"}

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

watch -c -t -n $argv[1] docker run --name "$DOCKER_RAND_ID" --rm -t \
  -e KUBE_EDITOR=vim \
  -v $HOME/.kube/config:/root/.kube/config \
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  frealmyr/cloud-sdk-editors:latest kubectl $kns get nodes
}
