#!/usr/local/bin/zsh

#
# Run kubectl commands, GKE requires gcloud for helpers.
# Without interactive mode on the container, for some odd use-cases.
#
function kportf() {
: ${1?"kportf PODNAME PORT"}

pod=$argv[1]
port=$argv[2]

# Add a random id to the docker container, so that we can run multiple instances
if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID="$RANDOM"
fi

  docker run --name "$DOCKER_RAND_ID" --rm \
  -u 1000:1000 \
  -v $(pwd):$(pwd) \
  --net=host \
  -w $(pwd) \
  -e KUBE_EDITOR=vim \
  -v $HOME/.config/kube:/home/clitools/.kube \
  -v $HOME/.config/gcloud:/home/clitools/.config/gcloud \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl $kns port-forward $pod $port:$port
}
