#!/usr/local/bin/zsh

#
# Use stern to tail multiple k8s resources
#
function ktail() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.kube/config:/home/clitools/.kube/config \
  -v $HOME/.config/gcloud:/home/clitools/.config/gcloud \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest stern $kns $argv[*]
}
