#!/usr/local/bin/zsh

#
# Run kubectl commands, GKE requires gcloud for helpers
#
function k() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

#if [[ -z "$K8S_VERSION" ]]; then
#  K8S_VERSION="1.14"
#fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -e KUBE_EDITOR=vim \
  -v $HOME/.kube/config:/root/.kube/config \
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  frealmyr/cloud-sdk-editors:latest kubectl $kns $argv[*]
}

#
# Sets namespace by using a local variable with --namespace=argv, this enables seperate namespaces in sessions
#
function kns() {

if [[ -z $argv[1] ]]; then
  unset kns
else
  kns=--namespace=$argv[1]
fi
}


#
# List every kubectl context available
#
function kcls() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.14"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/config:/.kube/config \
  bitnami/kubectl:$K8S_VERSION config get-contexts
}

#
# Set the active kubectl context
#
function kset() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.14"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/:/.kube/ \
  bitnami/kubectl:$K8S_VERSION config use-context $argv[1]
}

#
# Get the active kubectl context
#
function kcc() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.14"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/:/.kube/ \
  bitnami/kubectl:$K8S_VERSION config view --current
}

#
# Rename the active kubectl context
#
function kcrename() {

: ${1?"Usage: kcmv new_context_name"}

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.14"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/:/.kube/ \
  bitnami/kubectl:$K8S_VERSION config rename-context $(kcc config current-context | tr -d '\r') $argv[1]
}

#
# GKE, pull k8s credentials from google cloud.
#
function kpull() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube:/root/.kube \
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  frealmyr/cloud-sdk-editors:latest gcloud beta container clusters get-credentials $argv[1] --region europe-north1 --project $argv[2]
}
