#!/usr/local/bin/zsh

#
#  Watch pods for changes
#
function kwhatever() {
: ${1?"kwhatever SECONDS"}

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

watch -c -t -n $argv[1] docker run --name "$DOCKER_RAND_ID" --rm -t \
  -u 1000:1000 \
  -v $HOME/.config/kube:/home/clitools/.kube \
  -v $HOME/.config/gcloud:/home/clitools/.config/gcloud \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl $kns $argv[2] $argv[3] $argv[4] $argv[5]
}
