#!/usr/local/bin/zsh

# Run yaml-link in dir using docker

function lint-yaml() {

docker run -it --rm \
  -u 1000:1000 \
  -v $(pwd):$(pwd) \
  -w /$(pwd) \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest yamllint -d "{extends: default, rules: {document-start: disable, brackets: disable, braces: disable, line-length: {max: 200}}}" . | grep -vwE "syntax error: expected the node content, but found '-'"
}
