#!/usr/local/bin/zsh

# Run yaml-link in dir using docker

function lint-yaml() {

docker run -it --rm \
  -v $(pwd):$(pwd) \
  -w /$(pwd) \
  sdesbure/yamllint:latest yamllint -d "{extends: default, rules: {document-start: disable, brackets: disable, braces: disable, line-length: {max: 200}}}" .
}
