#!/usr/local/bin/zsh

# Run Terraform commands with docker

function tf() {

mnt="/root/terraform"

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

ENV_VARS_TF=$(compgen -v | grep TF_ | awk '{print $1}' | cut -f1 -d= | sed 's \(.*\) \1=$\1 ' | sed 's/^/ -e / ' | sed 's/$/ \\ / ')
#$(compgen -v | grep GOOGLE_ | awk '{print $1}' | cut -f1 -d= | sed 's/^/  -e / ')
#$(compgen -v | grep TF_ | awk '{print $1}' | cut -f1 -d= | sed 's/^/  -e / ')

echo $TF_VARS

docker run --name "$DOCKER_RAND_ID" -it --rm \
  -v /tmp:/tmp \
  -v $(pwd):$mnt \
  -w /$mnt \
  -v $HOME/.kube:/root/.kube \
  $ENV_VARS_TF \
  bulderbank/gcp-tools:latest terraform $argv[*]
}
