#!/usr/local/bin/zsh

#
# Runs terraform validate every x seconds in the current folder
#
function tfvalidate () {
: ${1?"tfvalidate SECONDS"}

watch -b -c -n $argv[1] 'zsh -c "source ${HOME}/.config/zsh/functions/tf; tf validate"'
}
