#!/usr/local/bin/zsh

#
# Run Terraform apply
#
function tfapply() {

if [[ -n $(echo *.tf) ]]
then
  tf apply -parallelism=25 $(for filename in env/$ENVIRONMENT/*.tfvars; do printf "-var-file=$filename " ; done)
else
  echo "There are no Terraform files in this folder, aborting.."
fi

}
