#!/usr/local/bin/zsh

# Run Terraform commands with docker

function tf() {

mnt="/root/terraform"

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

# ENV_VARS_TF=$(compgen -v | grep TF_ | awk '{print $1}' | cut -f1 -d= | sed 's \(.*\) \1=$\1 ' | sed 's/^/ -e / ' | sed 's/$/ \\ / ')
# ENV_VARS_GCP=$(compgen -v | grep GOOGLE_ | awk '{print $1}' | cut -f1 -d= | sed 's \(.*\) \1=$\1 ' | sed 's/^/ -e / ' | sed 's/$/ \\ / ')
# ENV_VARS+="$ENV_VARS_TF $ENV_VARS_GCP"

docker run --name "$DOCKER_RAND_ID" -it --rm \
  -u 1000:1000 \
  -v /tmp:/tmp \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.kube/config:/home/clitools/.kube/config \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest terraform $argv[*]
}

  # $(echo $ENV_VARS_TF) \
  # $(echo $ENV_VARS_GCP) \