---
- hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: shell - check if brew is present
      command: brew -v
      register: brew_present
      ignore_errors: true

    - name: shell - install brew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_present is failed

    - name: brew - taps
      homebrew_tap:
        name:
          - FelixKratz/formulae # borders, https://github.com/FelixKratz/JankyBorders
          - asmvik/formulae # yabai, skhd, https://github.com/asmvik/yabai, https://github.com/asmvik/skhd
          - jurplel/tap # instant-space-switcher

    ###########
    ## Brews ##
    ###########

    - name: brew - cli tools (common)
      homebrew:
        name:
          - bat
          - blueutil
          - borders
          - btop
          - coreutils
          - curl
          - cloc
          - direnv
          - docker
          - docker-buildx
          - docker-credential-helper
          - ed
          - fd
          - findutils
          - fzf
          - gawk
          - git
          - git-delta
          - gnu-sed
          - gnu-tar
          - htop
          - gnupg
          - gnuplot
          - grep
          - jq
          - kind
          - osx-cpu-temp # dependency for btop
          - less
          - make
          - mise
          - neovim
          - parallel
          - pinentry-mac # dependency for gnupg
          - skhd
          - sleepwatcher
          - tree
          - vim
          - watch
          - wget
          - xz
          - yabai
          - yq
          - zsh
          - zoxide
        state: present

    - name: brew - cli tools (personal)
      homebrew:
        name:
          - fastfetch
          - exiftool
          - mlx-lm
          - opencode
        state: present
      when: ansible_facts['hostname'] == "fm-macbook"

    - name: brew - cli tools (work)
      homebrew:
        name:
          - opencode
          - graphviz
        state: present
      when: ansible_facts['hostname'] == "K4W6XM73X6"

    ###########
    ## Casks ##
    ###########

    - name: brew - casks gui tools (common)
      homebrew_cask:
        name:
          - betterdisplay
          - breaktimer
          - firefox
          - font-fira-code-nerd-font
          - font-fira-mono-nerd-font
          - font-atkinson-hyperlegible
          - instant-space-switcher
          - obsidian
          - podman-desktop
          - stats
          - the-unarchiver
          - visual-studio-code
          - wezterm
        state: present

    - name: brew - casks gui tools (personal)
      homebrew_cask:
        name:
          - affinity-designer
          - affinity-photo
          - affinity-publisher
          - audacity
          - balenaetcher
          - calibre
          - darktable
          - digikam
          - google-chrome
          - halloy
          - hyperbackupexplorer
          - jellyfin-media-player
          - keepassxc
          - musicbrainz-picard
          - netnewswire
          - netspot
          - raspberry-pi-imager
          - rawtherapee
          - starsector
          - steam
          - sweet-home3d
          - synology-drive
          - tailscale-app
          - topaz-denoise-ai
          - transmission
          - utm
        state: present
      when: ansible_facts['hostname'] == "fm-macbook"

    - name: brew - casks gui tools (work)
      homebrew_cask:
        name:
          - jetbrains-toolbox
          - slack
          - xbar
        state: present
      when: ansible_facts['hostname'] == "K4W6XM73X6"
