k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /Users/fredrick/.config/k9s/screen-dumps
  refreshRate: 5
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: false
    reactive: true
    noIcons: false
    defaultsToFullScreen: false
    skin: dracula
  skipLatestRevCheck: true
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
  imageScans:
    enable: false
    exclusions:
      namespaces:
        - kube-system
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
