---
- hosts: localhost
  become: yes
  become_user: fredrick

  tasks:
  - name: git fetch configs to homefolder
    args:
      chdir: "~/"
    shell: |
      git init
      git remote add origin https://github.com/frealmyr/dotfiles-configs.git
      git fetch origin
      git checkout -b main --track origin/main
    register: configs_result
    failed_when:
      - configs_result.rc == 1 or configs_result.rc == 128 and not "'already exists' in configs_result.stderr"

  - name: set zsh as default shell
    shell: chsh -s $(which zsh) fredrick
    become_user: root
