---
- hosts: localhost
  become: yes
  tasks:
    # - name: install apt packages requirements
    #   apt:
    #     pkg:
    #     - apt-transport-https
    #     - ca-certificates
    #     - curl
    #     - gnupg-agent
    #     - software-properties-common

    # - name: add docker signing key
    #   ansible.builtin.apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: add docker apt repository
    #   ansible.builtin.apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    #     state: present

    # - name: install apt packages
    #   apt:
    #     pkg:
    #     - docker-ce
    #     - docker-ce-cli
    #     - containerd.io

    # - name: add user to docker group
    #   user: name=fredrick
    #         groups=docker
    #         append=yes

    # # gpg, pass and docker-credentail-helper
    # # note: i dont use pass for anything else, bitwarden rules
    # - name: install apt packages requirements
    #   apt:
    #     pkg:
    #     - gpg
    #     - pass

    - name: delete any existing gpg key
      shell: |
        gpg --list-keys | grep -E '[A-Z0-9.]{40}$' | tr -d ' ' | while read -r line ; do
          gpg --batch --yes --delete-secret-keys --fingerprint $line
          gpg --batch --yes --delete-keys --fingerprint $line
        done
      become_user: fredrick

    - name: deleting existing pass configuration
      ansible.builtin.file:
        path: ~/.password-store/.gpg-id
        state: absent
      become_user: fredrick

    # - name: create gpg key
    #   shell: |
    #     {
    #     gpg --batch --generate-key <<EOF
    #         %echo Generating a random password key for docker credential pass store...
    #         Key-Type: default
    #         Subkey-Type: default
    #         Name-Real: Docker Rocks
    #         Name-Comment: Random password priv/pub for docker credentials
    #         Name-Email: docker@rocks.srsly
    #         Expire-Date: 0
    #         Passphrase: {{ docker_password }}
    #     EOF
    #     } 1> /dev/null
    #     gpg --list-public-keys --with-colons \
    #       | sed -ne '/^pub:/,/^fpr:/ { /^fpr:/ p }' \
    #       | cut -d: -f10
    #   register: gpg_pub_key
    #   become_user: fredrick

    # - name: initializing pass with gpg public key
    #   shell: pass init {{ gpg_pub_key.stdout }}
    #   become_user: fredrick

    # - name: download docker-credential-helpers
    #   get_url:
    #     url="https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz"
    #     dest="/tmp/docker-credential-pass-v0.6.4-amd64.tar.gz"

    # - name: extract docker-credential-pass into /usr/local/bin
    #   ansible.builtin.unarchive:
    #     src: /tmp/docker-credential-pass-v0.6.4-amd64.tar.gz
    #     dest: /usr/local/bin

    # - name: change perm of "/usr/local/bin/docker-credential-pass", adding "+x"
    #   file: dest=/usr/local/bin/docker-credential-pass mode=a+x

    # - name: enable pass backend in docker credsStore
    #   ansible.builtin.lineinfile:
    #     path: ~/.docker/config.json
    #     line: "{ 'credsStore': 'pass' }"
    #     create: yes
    #   become_user: fredrick
