---
- hosts: localhost
  become: yes
  vars:
    - target_package: cadmus
    - target_url: https://github.com/josh-richardson/cadmus/releases/latest/download/cadmus.deb
  tasks:
    - name: Check if {{ target_package }} is installed
      command: dpkg-query -W target_package
      register: target_package_check_deb
      failed_when: target_package_check_deb.rc > 1
      changed_when: target_package_check_deb.rc == 1

    - name: Download {{ target_package }}
      get_url:
        url="{{ target_url }}"
        dest="/tmp/{{ target_package }}.deb"
      when: target_package_check_deb.rc == 1

    - name: Install {{ target_package }}
      apt: deb="/tmp/{{ target_package }}.deb"
      when: target_package_check_deb.rc == 1

    - name: Delete {{ target_package }} leftovers
      ansible.builtin.file:
        path: /tmp/{{ target_package }}.deb
        state: absent
