---
- hosts: localhost
  become: yes
  tasks:
    - name: update & upgrade apt packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 3600

    - name: install apt packages
      apt:
        pkg:
        - bat
        - curl
        - dunst
        - git
        - firefox
        - htop
        - mc
        - python3-pip
        - regolith-look-dracula
        - snapd
        - tmux
        - zsh

    - name: remove package regolith-rofication
      apt:
        name: regolith-rofication
        state: absent
        purge: yes

    - name: install apt no-recommends
      apt:
        install_recommends: no
        pkg:
          - libreoffice-calc
          - libreoffice-gtk3

    - name: clean & remove apt packages
      apt:
        autoclean: yes
        autoremove: yes

    - name: install snap packages
      community.general.snap:
        name:
          - beekeeper-studio
          - bitwarden
          - discord
          - spotify
          - newsflash
          - teams

    - name: install snap classic packages
      community.general.snap:
        classic: yes
        name:
          - code
          - google-cloud-sdk
          - slack

- name: install cadmus
  import_playbook: packages-cadmus.yml
