import = [
    "~/.config/alacritty/themes/dark.toml"
]

[cursor]
blink_interval = 300

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 14

[font.normal]
family = "Monaco"
style = "Regular"

[window]
decorations = "none"
opacity = 1
dynamic_padding = true
padding = { x = 3, y = 3 }
