---
- hosts: localhost
  become: yes
  roles:
    - ansible-role-firefox

  vars:
    firefox_home: ~/.mozilla/firefox

    firefox_profiles:
      - name: home
        extensions:
          - random-agent-spoofer
      - name: work
        extensions: []

    firefox_preferences:
      browser.safebrowsing.enabled: 'true'
      geo.ip: 'false'

    firefox_profile_preferences:
      alice:
        browser.safebrowsing.enabled: 'false'
        browser.safebrowsing.malware.enabled: 'false'

  pre_tasks:
    - name: install role requirements
      pip: name={{ item }} state=present
      with_items:
        - xmltodict
        - requests

  roles:
    - firefox
