---
- hosts: localhost
  become: true
  tasks:
    - name: update & upgrade apt packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 3600

    - name: install apt packages
      apt:
        pkg:
        - bat
        - chromium-browser
        - firefox
        - htop
        - joplin
        - mc
        - regolith-look-dracula
        - snapd
        - tmux
        - zsh

    - name: install apt no-recommends
      apt:
        install_recommends: no
        pkg:
          - libreoffice-calc
          - libreoffice-gtk3

    - name: clean & remove apt packages
      apt:
        autoclean: yes
        autoremove: yes

    - name: Install community.general.snap
      include_role: 
        name: community.general.snap

    - name: install snap packages
      community.general.snap:
        name:
          - beekeeper-studio
          - bitwarden
          - discord
          - spotify
          - teams

    - name: install snap classic packages
      community.general.snap:
        classic: yes
        name:
          - code
          - google-cloud-sdk
          - slack

# regolith-look set dracula
# regolith-look refresh
# mkdir -p ~/.config/regolith/picom
# cp /etc/regolith/picom/config ~/.config/regolith/picom
