[tools]
argo = "latest"
argo-rollouts = "latest"
argocd = "latest"
azure-kubelogin = "latest"
cilium-cli = "latest"
flux2 = "latest"
helm = "latest"
k9s = "latest"
krew = "latest"
kubectl = "latest"
stern = "latest"
terraform = "latest"
terraform-docs = "latest"
